### PR TITLE
Adding quoting to all MySql fastsync tap and Snowflake target to allo…

### PR DESCRIPTION
**Pull request by guy-adams**
…w source table and column names with swhitespace and target table and column names with either whitespace, or using reserved works (like 'group')

If there are things I need to do to improve this pull request please let me know. I've tested this against multiple mysql sources with spaces in table and column names and snowflake columns with reserved names.

### CODE REVIEW

**Comment by koszti** [comment]
@guy-adams we should have equivalent changes https://github.com/transferwise/pipelinewise-target-snowflake repo to keep fastsync and singer functionalities in sync.

Do you have any PR that addresses the same issue in target-snowflake in the above repo?

**Comment by guy-adams** [comment]
No, but I can add it - leave it with me!

**Comment by koszti** [comment]
@guy-adams this is great but please be careful with quoting column names, especially on the target-snowflake side. We want to keep the not case sensitive SQL behaviour in every target so all the below SQL should give the same result:
SELECT columnone FROM myschema.MYTABLE
SELECT columnOne FROM mySchema.myTable
SELECT COLUMNone FROM MYSCHEMA.MyTaBlE

If we quote to the table and column names in target then probably we need to use it in every SQL (SELECT * FROM myschema."myTable") in the target DB as well. This is not a great experience when writing queries and we'd like to avoid it.

Related to https://github.com/transferwise/pipelinewise/issues/242

**Comment by guy-adams** [comment]
Dropping this pull request to handle a different way

**Pull request closed without merging**
