### PR TITLE
Add extra_log parameter to CLI

### PR DESCRIPTION
**Pull request by fabien-sarcel**
Extra option to get tap-run and fastsync log output into std-out (#222 ).

I run PipelineWise Docker with Airflow (_DockerOperator_) and I need this option to see all the logs into Airflow.

### CODE REVIEW

**Comment by guy-adams** [comment]
Thanks for this - this will be really useful for us running in Docker too!

**Comment by koszti** [comment]
@fabien-sarcel this is great. can you please add a line into the documentation about extra_log parameter at https://transferwise.github.io/pipelinewise/user_guide/cli.html ?
The editable RST format is at https://github.com/transferwise/pipelinewise/blob/master/docs/user_guide/cli.rst

thanks

**Comment by ivan-transferwise** [comment]
Looks good 👍

**Comment by fabien-sarcel** [comment]
I looked at the documentation and I'm not very comfortable with it. I haven't work with Sphinx yet, but above all I'm not sure where I should put the extra_log option (there is no mention of existing log and debug options...).

Moreover, in the HTML documentation, options are rendered with 1 hyphen instead of 2.
I tried to change it without success, so I looked at the Airflow documentation (https://airflow.apache.org/cli.html#Sub-commands:)
and I saw that those command options are automatically generated.
Maybe that's something we should look into ?

**Comment by koszti** [comment]
@fabien-sarcel no worries I added it to the doc page and now it got merged. Thank you for contributing.

**Pull request merged**
