### PR TITLE
[NO-REF] Support MySQL spatial types in fastsync

### PR DESCRIPTION
**Pull request by henriblancke**
## Problem

`pipelinewise` and `pipelinewise-tap-mysql` currently don't support the MySQL [spatial data types](https://dev.mysql.com/doc/refman/5.7/en/spatial-type-overview.html)

## Proposed changes

This change adds support for spatial data types by converting them to geojson by using MySQLs `ST_AsGeoJSON` function.

## Types of changes

What types of changes does your code introduce to PipelineWise?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update (if none of the other choices apply)

## Checklist

- [x] I have read the [CONTRIBUTING](../CONTRIBUTING.md) doc
- [x] Description above provides context of the change
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] Unit tests for changes (not needed for documentation changes)
- [ ] CI checks pass with my changes
- [x] Bumping version in `setup.py` is an individual PR and not mixed with feature or bugfix PRs
- [ ] Commit message/PR title starts with `[AP-NNNN]` (if applicable. AP-NNNN = JIRA ID)
- [ ] Branch name starts with `AP-NNN` (if applicable. AP-NNN = JIRA ID)
- [ ] Commits follow "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)"
- [ ] Relevant documentation is updated including usage instructions

### CODE REVIEW

**Comment by koszti** [comment]
`geometry` types are mapped two times. Currently it's converted to `hex` [here](https://github.com/transferwise/pipelinewise/blob/694d817b8ca767839408152d05c56043f737eaa9/pipelinewise/fastsync/commons/tap_mysql.py#L208). This PR will be a breaking change and all the existing tables with `geometry` column will be loaded into a new column. This should be fine but we need to be careful. 

We need to extend the end to end test cases and add the new column types [here](https://github.com/transferwise/pipelinewise/blob/678a6f0fad9097a253234357b5628dd979481ff8/tests/db/tap_mysql_data.sql#L277) and cover with new scenarios if possible.

**Comment by henriblancke** [comment]
@koszti thanks for the review! I updated the PR to reflect your requested changes:

1. `geometry` is no longer converted to `hex`
2. I added e2e tests and added some new test scenarios
3. Postgres now loads spatial types as `jsonb` and snowflake as `variant`

I also made the requested changes in the tap-mysql repo [here](https://github.com/transferwise/pipelinewise-tap-mysql/pull/36)

**Comment by koszti** [comment]
thanks @henriblancke . I made a few changes in this PR and added redshift compatibility and test cases.

Can you please merge https://github.com/henriblancke/pipelinewise/pull/1 into this PR?

**Comment by henriblancke** [comment]
@koszti great! Thanks! PR is merged 🚀

**Review by koszti — APPROVED** [review]

**Pull request merged**
