### PR TITLE
Detected column types are not the same between fast sync and db sync

### PR DESCRIPTION
**Pull request by mlavoie-sm360**
### Describe the bug
When fast syncing a table that has columns with the `mediumint` type, the column would be first cast as a `varchar` and then recast (new column created) as an `int` when synced normally.

### Steps To Reproduce
Synchronize a large table that contains a column with `mediumint` type. The first time it will fast sync as `varchar`, the second time it will db sync and create a new column with the proper type.

### Expected behavior
Fast syncing and normal syncing should behave the same.

### CODE REVIEW

**Comment by Samira-El** [comment]
Hey, it's been a while since this PR has been created, a lot of things have changed and the PR has merge conflicts, can you fix them? we'll gladely consider merging it.
Thanks for the PR btw.

**Comment by Samira-El** [comment]
Hey, thanks for the conflict fix, I have to ask one more thing tho, you're making a PR from your own fork, unfortunatly, our CI checks/builds are only triggered if PR is made from a branch in this same repo, so can you create a branch in this repo and port your changes there so that the CI checks work? 
Thanks :)

**Comment by mlavoie-sm360** [comment]
Hi @Samira-El, is it possible I don't seem to have permission to create branches and commit code directly in this repo?

**Comment by Samira-El** [comment]
Hey, I just realized that external contributors have to fork the repo, my apologies.
I'll look into your PR next week to make sure it passes our tests and then run it against my fellow maintainers to see if we can proceed with the merge.
This PR touches Snowflake which is our main target at TranferWise so we tend to be pretty careful with code changes to it.

**Comment by mlavoie-sm360** [comment]
Thanks Samira, if the snowflake portion is an issue, let me know, the part I am most concerned about is redshift ;)

**Comment by Samira-El** [comment]
Hey, I looked through your PR, some of the changes here require updating tap-mysql for FastySync and Singer to be in sync.

Can you please rollback the changes to Snowflake if it's not your target target ;).

Now re Redshift:
1. you added the following types: `integer`, `dec` and `year`, these are not processed by tap-mysql [here](https://github.com/transferwise/pipelinewise-tap-mysql/blob/3789e673ca81d76b7a47457bd7483edb1eb294ea/tap_mysql/__init__.py#L61), you would need to add them to the list and assign them the right type.
2. The integers types in FastSync are mapped to `Numeric Null`, however, in target-redshift it's mapping integers to `Numeric` without the null constraint [here](https://github.com/transferwise/pipelinewise-target-redshift/blob/a7fed8b76a19e3c6bebcc39bbd8a127abbc9f38f/target_redshift/db_sync.py#L72).
 
Let me know if you need anymore clarification and whether you wanna make the changes above.

**Comment by mlavoie-sm360** [comment]
I might need more clarifications, but I'll give it a shot first. I can rollback the changes to Snowflake too.

**Comment by koszti** [comment]
addressed by https://github.com/transferwise/pipelinewise/pull/457.
Changes made only in fastsync components and added end to end tests.

**Comment by koszti** [comment]
https://github.com/transferwise/pipelinewise/pull/457 merged and released as part of PPW 0.17.0

**Pull request closed without merging**
