### PR TITLE
Convert `NamedTuple` to `dataclass`

### PR DESCRIPTION
**Pull request by judahrand**
## Problem

- The `namedtuples` with overridden `__init__` methods are really, really ugly.

## Proposed changes

- Use `dataclasses`

_Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request. 
If it fixes a bug or resolves a feature request, be sure to link to that issue._

## Types of changes

What types of changes does your code introduce to PipelineWise?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Documentation Update (if none of the other choices apply)

## Checklist

- [x] I have read the [CONTRIBUTING](../CONTRIBUTING.md) doc
- [x] Description above provides context of the change
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] Unit tests for changes (not needed for documentation changes)
- [x] CI checks pass with my changes
- [x] Bumping version in `setup.py` is an individual PR and not mixed with feature or bugfix PRs
- [x] Commit message/PR title starts with `[AP-NNNN]` (if applicable. AP-NNNN = JIRA ID)
- [x] Branch name starts with `AP-NNN` (if applicable. AP-NNN = JIRA ID)
- [x] Commits follow "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)"
- [x] Relevant documentation is updated including usage instructions

### CODE REVIEW

**Comment by judahrand** [comment]
@Samira-El Test failure isn't me as far as I can tell.

**Comment by Samira-El** [comment]
Thanks Judah for this, I didn't like that either but it made it to master branch 🤷🏽 .

How come the tests ran by themselves, they usually require someone to approve to run? 🤔 

I'm submitting a fix for e2e tests, it's becoming annoying.

**Comment by judahrand** [comment]
> How come the tests ran by themselves, they usually require someone to approve to run? 🤔

I think it's because I've had a PR merged in the past? So I'm no longer a first time contributor? That's how I've seen it work on some other repos anyway.

**Comment by Samira-El** [comment]
> > How come the tests ran by themselves, they usually require someone to approve to run? thinking
> 
> I think it's because I've had a PR merged in the past? So I'm no longer a first time contributor? That's how I've seen it work on some other repos anyway.

you're right, just found a setting for this.

**Comment by Samira-El** [comment]
Can you rebase, just pushed a fix to e2e tests?

**Review by Samira-El — APPROVED** [review]

**Pull request merged**
