### PR TITLE
Feature/implement jinja template rendering

### PR DESCRIPTION
**Pull request by pbegle**
## Problem

This PR implements functionality that allows for the usage of environment variables in YAML files as mentioned in issue #203 and #223.

## Proposed changes

Added a small change that allows the usage of jinja templates to use environment variables in YAML configuration files. This approach evaluates the environment variables when importing a project using `pipelinewise import`.

## Types of changes

What types of changes does your code introduce to PipelineWise?

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update (if none of the other choices apply)

## Checklist

- [x] I have read the [CONTRIBUTING](../CONTRIBUTING.md) doc
- [x] Description above provides context of the change
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] Unit tests for changes (not needed for documentation changes)
- [ ] CI checks pass with my changes
- [ ] Bumping version in `setup.py` is an individual PR and not mixed with feature or bugfix PRs
- [ ] Commit message/PR title starts with `[AP-NNNN]` (if applicable. AP-NNNN = JIRA ID)
- [ ] Branch name starts with `AP-NNN` (if applicable. AP-NNN = JIRA ID)
- [x] Commits follow "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)"
- [ ] Relevant documentation is updated including usage instructions

Test suite passes, with the exception of 1 unrelated test which was already failing in the `master` branch.

### CODE REVIEW

**Comment by Samira-El** [comment]
Hey Peter, 

Thank you for the PR, this feature is very cool and might be useful to us! 

Can you please add unit tests to cover this change?

**Comment by pbegle** [comment]
Hi Samira, I just pushed a commit where I added a test case to the `tests/units/cli/test_cli_utils.py:test_yaml_loader` test and a corresponding YAML file which includes some jinja environment variables defined.

**Comment by Samira-El** [comment]
Thanks for the changes!

**Review by koszti — APPROVED** [review]

**Review by Samira-El — APPROVED** [review]

**Comment by koszti** [comment]
@pbegle would that be possible the document this feature?

I'm not sure where is the good place in the docs, maybe a new section and example at around https://transferwise.github.io/pipelinewise/installation_guide/creating_pipelines.html#generating-sample-pipelines ?

We can also consider to update the sample YAML files in [cli/samples](https://github.com/transferwise/pipelinewise/blob/master/pipelinewise/cli/samples] and add example with env vars, especially for passwords.

What do you think?

**Comment by pbegle** [comment]
Yeah, I can work on a new PR to add some documentation on how to use this feature.

**Pull request merged**
