### PR TITLE
Update tested Python versions

### PR DESCRIPTION
**Pull request by judahrand**
## Problem

- Python 3.6 is end of life.
- Python 3.9 and 3.10 are currently untested.

## Proposed changes

- Remove Python 3.6 from test matrix
- Add Python 3.9 to test matrix.
- Python 3.10 does not pass so don't add it.
- Set the correct `python_requires` in `setup.py`

_Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request. 
If it fixes a bug or resolves a feature request, be sure to link to that issue._

## Types of changes

What types of changes does your code introduce to PipelineWise?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Documentation Update (if none of the other choices apply)

## Checklist

- [x] I have read the [CONTRIBUTING](../CONTRIBUTING.md) doc
- [x] Description above provides context of the change
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] Unit tests for changes (not needed for documentation changes)
- [x] CI checks pass with my changes
- [x] Bumping version in `setup.py` is an individual PR and not mixed with feature or bugfix PRs
- [x] Commit message/PR title starts with `[AP-NNNN]` (if applicable. AP-NNNN = JIRA ID)
- [x] Branch name starts with `AP-NNN` (if applicable. AP-NNN = JIRA ID)
- [x] Commits follow "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)"
- [x] Relevant documentation is updated including usage instructions

### CODE REVIEW

**Comment by judahrand** [comment]
@Samira-El Test failure isn't me as far as I can tell.

**Comment by Samira-El** [comment]
Can you rebase, just pushed a fix to this?

**Comment by Samira-El** [comment]
Judah, looks like CI isn't happy.

**Comment by judahrand** [comment]
> Judah, looks like CI isn't happy.

Whoops! My mistake! Should be fixed.

**Review by Samira-El — COMMENTED** [review]
Lgtm, thanks for this contribution!

**Review by Samira-El — APPROVED** [review]

**Pull request merged**
