### PR TITLE
Added the ability to use environmental variables in json files

### PR DESCRIPTION
**Pull request by sokser**
This uses Jinja2 to preparse config files that are loaded into JSON. It attempts to replace `{{ VARIABLE }}` with the corresponding environmental variable.

### CODE REVIEW

**Comment by vitorbaptista** [comment]
Looking forward for this to be merged!

Personally, I'd rather have something like `{{ env['MY_ENV'] }}` instead of `{{ MY_ENV }}`. This should be simply changing `template.render(**os.getenv)` to `template.render(env=os.environ)` (maybe `os.environ.copy()` to avoid passing the actual env dict)

**Comment by koszti** [comment]
I think dynamically rendering the JSON files will have some problems because in this case every tap and target connector should do the same thing well and I think that's not the case in the connectors and they will raise Invalid JSON example at runtime. Remember, this pipelinewise library is only a "wrapper" on top of other singer connectors. It's generating JSON config files for singer connectors from a common YAML structure and running the singer taps/targets individually.

Instead of rendering the JSON we can try to template the YAML files with similar methods. But please also note if we will use env variables in the YAML (and this was the original question #203), then it will be evaluated only when importing the project by `pipelinewise importing --dir ..`! (the time when generating singer compatible JSON files from the common pipelinewise YAML)


If you think that evaluating environment variables only when importing the project then it's a very similiar change to this PR but in the YAML at around https://github.com/transferwise/pipelinewise/blob/master/pipelinewise/cli/utils.py#L157

What do you think?

**Comment by johnoscott** [comment]
I agree dynamic JSON is not appropriate for PipelineWise since it is the output of the YAML config.

I do support dynamic YAML with environment variables for USE CASES such as supporting different deployment stages (DEV, TEST, PROD etc).  [DBT](https://www.getdbt.com/) comes to mind as an example project that does this well I think.

**Comment by guy-adams** [comment]
Does this need a documentation update too?

**Comment by Samira-El** [comment]
Hey,
This should be possible now thanks to #588.

**Comment by johnoscott** [comment]
Awesome, awesome, awesome !

**Pull request closed without merging**
