### PR TITLE
NO-REF Include tinyint(1) unsigned in type conversion for fastsync

### PR DESCRIPTION
**Pull request by henriblancke**
## Problem

We recently started seeing some issues during full resyncs of a couple of mysql tables with columns that have type `tinyint(1) unsigned`. Part of the problem is that we have been inconsistent with the use of `tinyint(1)` and `tinyint(1) unsigned` for boolean columns. 

What we saw was that, during the initial fastsync, columns with `tinyint(1) unsigned` were identified as `number` and then later converted to boolean in the incremental syncs because the tap-mysql discover step identifies them correctly: https://github.com/transferwise/pipelinewise-tap-mysql/blob/master/tap_mysql/discover_utils.py#L182. It looks like the fastsync component is doing a hard check for `tinyint(1)` and not taking into account that it could be `unsigned`.

## Proposed changes

During mysql -> snowflake fastsync check if the column type starts with `tinyint(1)`

## Types of changes

What types of changes does your code introduce to PipelineWise?
_Put an `x` in the boxes that apply_

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update (if none of the other choices apply)

## Checklist

- [x] I have read the [CONTRIBUTING](../CONTRIBUTING.md) doc
- [x] Description above provides context of the change
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Unit tests for changes (not needed for documentation changes)
- [ ] CI checks pass with my changes
- [ ] Bumping version in `setup.py` is an individual PR and not mixed with feature or bugfix PRs
- [ ] Commit message/PR title starts with `[AP-NNNN]` (if applicable. AP-NNNN = JIRA ID)
- [ ] Branch name starts with `AP-NNN` (if applicable. AP-NNN = JIRA ID)
- [ ] Commits follow "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)"
- [ ] Relevant documentation is updated including usage instructions

### CODE REVIEW

**Comment by Samira-El** [comment]
Hey Henri, thank you for raising the issue and for this PR!

Can you please add the same change to `mysql -> pg` and `mysql->redshift`? Also, we would like to cover this change with tests, can you please add `tinyint(1) unsigned` to this [table](https://github.com/transferwise/pipelinewise/blob/f7020558c75e0ac1c17e8d8b154625272263ce84/tests/db/tap_mysql_data.sql#L277) and make sure the tests are passing?

**Comment by henriblancke** [comment]
@Samira-El thanks for the quick response! I added support for redshift and postgres and added the required test.

**Comment by Samira-El** [comment]
Hey Henri, thanks for the changes!

We're entering a code change freeze at TransferWise, so merging this PR will have to wait until Jan 2021.

**Comment by henriblancke** [comment]
@Samira-El sounds good! Happy holidays :)

**Review by Samira-El — APPROVED** [review]

**Pull request merged**
